version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "57:9a:2a:f2:b0:cc:79:6c:87:93:5f:d5:14:31:17:f9"
      - run:
          name: Run Setup Script
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy Master to Heroku
          command: |
            heroku git:remote -a is-it-raining-deploy
            git push --force git@heroku.com:is-it-raining-deploy.git HEAD:refs/heads/master
            heroku run python manage.py deploy
            heroku restart
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:  # only deploy when master successfully builds
          requires:
            - build
          filters:
            branches:
              only: master
